"""
Persistent Gemini cache for Streamlit Cloud deployment.

Problem: @st.cache_data only caches in memory. When the GitHub Actions pipeline
runs pre-warming, those caches exist in a separate process and don't transfer
to Streamlit Cloud.

Solution: This module persists Gemini results to disk (gemini_cache.json) during
the pipeline run. The dashboard loads from this file on startup, with automatic
invalidation when the file changes.

Cache Structure:
{
    "cache_key_hash": {
        "result": <cached_result>,
        "timestamp": <iso_timestamp>,
        "ttl_hours": 24
    }
}
"""

import hashlib
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

# Cache file path
_CACHE_FILE: Path | None = None

# In-memory cache loaded from disk
_DISK_CACHE: dict | None = None

# Track when we last loaded the cache (for invalidation)
_CACHE_LOAD_TIME: datetime | None = None
_CACHE_FILE_MTIME: float | None = None

# Cache TTL in hours (matches CACHE_TTL_SECONDS in gemini_ner_analysis.py)
CACHE_TTL_HOURS = 24

# How often to check if the file has changed (seconds)
FILE_CHECK_INTERVAL = 60  # Check every minute


def _get_cache_file() -> Path:
    """Get the cache file path (lazy import to avoid circular deps)."""
    global _CACHE_FILE
    if _CACHE_FILE is None:
        from paths import GEMINI_CACHE_JSON
        _CACHE_FILE = GEMINI_CACHE_JSON
    return _CACHE_FILE


def _should_reload_cache() -> bool:
    """
    Check if the cache file has been modified since we loaded it.

    This handles the case where the pipeline updates gemini_cache.json
    but the Streamlit app has an old copy in memory.
    """
    global _CACHE_FILE_MTIME, _CACHE_LOAD_TIME

    if _DISK_CACHE is None:
        return True  # Never loaded

    if _CACHE_LOAD_TIME is None:
        return True  # Never tracked

    # Don't check too frequently
    if datetime.now() - _CACHE_LOAD_TIME < timedelta(seconds=FILE_CHECK_INTERVAL):
        return False

    cache_file = _get_cache_file()
    if not cache_file.exists():
        return False

    current_mtime = cache_file.stat().st_mtime

    if _CACHE_FILE_MTIME is None or current_mtime > _CACHE_FILE_MTIME:
        print(f"Cache file changed (mtime: {current_mtime}), reloading...")
        return True

    # Update load time to prevent checking again immediately
    _CACHE_LOAD_TIME = datetime.now()
    return False


def get_cache_key(func_name: str, *args) -> str:
    """
    Generate a deterministic cache key from function name and arguments.

    Args:
        func_name: Name of the Gemini function
        *args: Arguments passed to the function (will be JSON-serialized)

    Returns:
        Hash string suitable for cache lookup
    """
    key_data = {
        "func": func_name,
        "args": args
    }
    key_str = json.dumps(key_data, sort_keys=True, default=str)
    return hashlib.sha256(key_str.encode()).hexdigest()[:32]


def load_disk_cache(force_reload: bool = False) -> dict:
    """
    Load the entire cache from disk.

    Automatically reloads if:
    - Cache hasn't been loaded yet
    - The underlying file has changed
    - force_reload=True is passed

    Returns:
        Dict of cache entries
    """
    global _DISK_CACHE, _CACHE_LOAD_TIME, _CACHE_FILE_MTIME

    # Check if we need to reload
    if not force_reload and _DISK_CACHE is not None:
        if not _should_reload_cache():
            return _DISK_CACHE

    cache_file = _get_cache_file()

    if not cache_file.exists():
        _DISK_CACHE = {}
        _CACHE_LOAD_TIME = datetime.now()
        _CACHE_FILE_MTIME = None
        return _DISK_CACHE

    try:
        with open(cache_file, 'r') as f:
            _DISK_CACHE = json.load(f)
        _CACHE_LOAD_TIME = datetime.now()
        _CACHE_FILE_MTIME = cache_file.stat().st_mtime
        print(f"Loaded Gemini cache: {len(_DISK_CACHE)} entries")
    except (json.JSONDecodeError, IOError) as e:
        print(f"Warning: Could not load Gemini cache: {e}")
        _DISK_CACHE = {}
        _CACHE_LOAD_TIME = datetime.now()
        _CACHE_FILE_MTIME = None

    return _DISK_CACHE


def load_from_disk_cache(cache_key: str) -> Any | None:
    """
    Load a cached result from disk.

    Args:
        cache_key: Key generated by get_cache_key()

    Returns:
        Cached result if valid and not expired, None otherwise
    """
    cache = load_disk_cache()  # Will auto-reload if file changed

    entry = cache.get(cache_key)
    if entry is None:
        return None

    # Check TTL
    try:
        timestamp = datetime.fromisoformat(entry.get("timestamp", ""))
        ttl_hours = entry.get("ttl_hours", CACHE_TTL_HOURS)

        if datetime.now() - timestamp > timedelta(hours=ttl_hours):
            # Expired
            return None

        return entry.get("result")
    except (ValueError, TypeError):
        return None


def save_to_disk_cache(cache_key: str, result: Any) -> None:
    """
    Save a result to the disk cache.

    Args:
        cache_key: Key generated by get_cache_key()
        result: The result to cache (must be JSON-serializable)
    """
    global _DISK_CACHE, _CACHE_FILE_MTIME

    cache = load_disk_cache()

    cache[cache_key] = {
        "result": result,
        "timestamp": datetime.now().isoformat(),
        "ttl_hours": CACHE_TTL_HOURS
    }

    # Write to disk
    cache_file = _get_cache_file()
    try:
        with open(cache_file, 'w') as f:
            json.dump(cache, f, indent=2, default=str)
        _CACHE_FILE_MTIME = cache_file.stat().st_mtime
    except IOError as e:
        print(f"Warning: Could not save Gemini cache: {e}")


def invalidate_cache() -> None:
    """Force cache invalidation - reload on next access."""
    global _DISK_CACHE, _CACHE_LOAD_TIME, _CACHE_FILE_MTIME
    _DISK_CACHE = None
    _CACHE_LOAD_TIME = None
    _CACHE_FILE_MTIME = None


def clear_disk_cache() -> None:
    """Clear the entire disk cache."""
    global _DISK_CACHE, _CACHE_LOAD_TIME, _CACHE_FILE_MTIME
    _DISK_CACHE = {}
    _CACHE_LOAD_TIME = datetime.now()
    _CACHE_FILE_MTIME = None

    cache_file = _get_cache_file()
    if cache_file.exists():
        cache_file.unlink()


def get_cache_stats() -> dict:
    """Get statistics about the cache."""
    cache = load_disk_cache()
    cache_file = _get_cache_file()

    valid_count = 0
    expired_count = 0
    now = datetime.now()

    for entry in cache.values():
        try:
            timestamp = datetime.fromisoformat(entry.get("timestamp", ""))
            ttl_hours = entry.get("ttl_hours", CACHE_TTL_HOURS)

            if now - timestamp > timedelta(hours=ttl_hours):
                expired_count += 1
            else:
                valid_count += 1
        except (ValueError, TypeError):
            expired_count += 1

    return {
        "total_entries": len(cache),
        "valid_entries": valid_count,
        "expired_entries": expired_count,
        "cache_file": str(cache_file),
        "file_mtime": _CACHE_FILE_MTIME,
        "last_loaded": _CACHE_LOAD_TIME.isoformat() if _CACHE_LOAD_TIME else None
    }
